name: Build & Deploy CMS
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_cms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clean up legacy SWA files
        run: |
          rm -f .github/workflows/azure-static-web-app-cms.yml
          rm -f staticwebapp.config.json
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build CMS (production)
        run: npx ng build --configuration production
      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli
      - name: Verify build output and deploy CMS
        env:
          AZURE_STATIC_WEB_APP_API_TOKEN_CMS: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN_CMS }}
        run: |
          ls -la dist/
          ls -la dist/qds/ || echo "dist/qds directory not found!"
          
          if [ -f "dist/qds/index.html" ]; then
            swa deploy dist/qds \
              --app-name STAPP-BooksPrinting-STG-02 \
              --env production \
              --deployment-token $AZURE_STATIC_WEB_APP_API_TOKEN_CMS \
              --verbose
          else
            find dist -name "index.html" -type f
            FOUND_INDEX=$(find dist -name "index.html" -type f | head -1)
            if [ ! -z "$FOUND_INDEX" ]; then
              DEPLOY_DIR=$(dirname "$FOUND_INDEX")
              echo "Deploying from directory: $DEPLOY_DIR"
              swa deploy "$DEPLOY_DIR" \
                --app-name STAPP-BooksPrinting-STG-02 \
                --env production \
                --deployment-token $AZURE_STATIC_WEB_APP_API_TOKEN_CMS \
                --verbose
            else
              echo "Could not find index.html in any subdirectory. Deployment failed."
              exit 1
            fi
          fi
